project:
    base_directory    : /Users/markconway/Projects
    file_extension    : csv
    project_name      : Santander
    sample_submission : True
    submission_file   : 'sample_submission'

data:
    drop              : ['ID']
    dummy_limit       : 200
    features          : '*'
    sampling          :
        option        : False
        method        : under_random
        ratio         : 0.0
    sentinel          : -1
    separator         : ','
    shuffle           : False
    split             : 0.4
    target            : TARGET
    target_value      : 1
    test              : 'test'
    test_labels       : False
    train             : 'train'

model:
    algorithms        : ['XGB']
    balance_classes   : False
    calibration       :
        option        : False
        type          : isotonic
    cv_folds          : 5
    estimators        : 2001
    feature_selection :
        option        : False
        percentage    : 5
        uni_grid      : [5, 10, 15, 20, 25]
        score_func    : f_classif
    grid_search       :
        option        : False
        iterations    : 100
        random        : True
        subsample     : True
        sampling_pct  : 0.2
    pvalue_level      : 0.01
    rfe               :
        option        : False
        step          : 100
    scoring_function  : roc_auc
    type              : classification

features:
    clustering        :
        option        : False
        increment     : 3
        maximum       : 30
        minimum       : 3
    counts            :
        option        : False
    encoding          :
        rounding      : 3
        type          : factorize
    genetic           :
        option        : False
        features      : 20
    interactions      :
        option        : True
        poly_degree   : 2
        sampling_pct  : 2
    isomap            :
        option        : False
        components    : 2
        neighbors     : 5
    logtransform      :
        option        : False
    numpy             :
        option        : False
    pca               :
        option        : False
        increment     : 3
        maximum       : 15
        minimum       : 3
        whiten        : False
    scipy             :
        option        : False
    text              :
        ngrams        : 1
        vectorize     : False
    tsne              :
        option        : False
        components    : 2
        learning_rate : 1000.0
        perplexity    : 30.0

pipeline:
    number_jobs       : -1
    seed              : 42
    verbosity         : 1

plots:
    calibration       : True
    confusion_matrix  : True
    importances       : True
    learning_curve    : True
    roc_curve         : True

xgboost:
    stopping_rounds   : 50
