# These are supported funding model platforms

github: [ScottfreeLLC]
custom: ['https://www.paypal.com/donate/?token=nbpC0QxltHUEObSgKi2ckhfyAz1BOa5jcYaaaSa0NwCwBQjl8BJzzxOlAVzx5MRYtA7PS0&country.x=US&locale.x=US']
